In [1]:
import numpy as np

In [2]:
list = [10, 20, 30]
list


[10, 20, 30]

In [3]:
arr1 = np.array(list)
arr1

array([10, 20, 30])

In [4]:
type(arr1)

numpy.ndarray

### nd = n-Dimensional

In [5]:
arr2 = np.arange(10, 20, 1) # (star, stop(non-inclusive), step-size)
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [6]:
list

[10, 20, 30]

In [7]:
list2 = [40, 50, 60]

In [8]:
list3 = [list, list2]
list3

[[10, 20, 30], [40, 50, 60]]

In [9]:
arr3 = np.array(list3)
arr3

array([[10, 20, 30],
       [40, 50, 60]])

In [10]:
arr3.shape

(2, 3)

In [11]:
arr3dim = np.array(
    [
        [
            [1, 2, 3], [3, 4, 5]
        ],
        [
            [5, 6, 7], [7, 8, 9]
        ]
        
    ]
        
)
arr3dim

array([[[1, 2, 3],
        [3, 4, 5]],

       [[5, 6, 7],
        [7, 8, 9]]])

In [12]:
arr3dim.shape

(2, 2, 3)

### Matrix Operations

In [13]:
list

[10, 20, 30]

In [14]:
list * 3

[10, 20, 30, 10, 20, 30, 10, 20, 30]

In [15]:
arr3dim * 3

array([[[ 3,  6,  9],
        [ 9, 12, 15]],

       [[15, 18, 21],
        [21, 24, 27]]])

In [16]:
arr1

array([10, 20, 30])

In [17]:
arr11 = np.array(list2)

In [18]:
arr11

array([40, 50, 60])

In [19]:
arr1.shape == arr11.shape

True

In [20]:
arr1 * arr11

array([ 400, 1000, 1800])

In [21]:
arr1 * arr3dim

array([[[ 10,  40,  90],
        [ 30,  80, 150]],

       [[ 50, 120, 210],
        [ 70, 160, 270]]])

## Lab

Create ndarrays of the following size:

1. One dimensional array with 12 elements(12)
2. Two dimensional array of size (3, 4)
3. Three dimensional array of size (2, 5, 4)

In [22]:
arr_1 = np.arange(1, 13, 1)
arr_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [23]:
arr_1.shape

(12,)

In [24]:
arr2dim = np.array(
    [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
)
arr2dim.shape

(3, 4)

In [56]:
arr3d_ = np.array(
    [
        [[1, 2, 3, 4], [6, 7, 8, 9], [10, 11, 12, 13], [14, 15, 16, 17], [18, 19, 20, 21]],
    [[11, 12, 13, 14], [16, 17, 18, 19], [20, 21, 22, 23], [24, 25, 26, 27], [28, 29, 30, 31]]
    ]
)
arr3d_.shape # for 3d (two rows, five in each row , four ints in each block)

(2, 5, 4)

In [59]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [62]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [71]:
np.ones((2, 5, 4), dtype=int)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [73]:
np.ones((2, 5, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [74]:
arr3

array([[10, 20, 30],
       [40, 50, 60]])

In [76]:
np.array(list3, dtype=float)

array([[10., 20., 30.],
       [40., 50., 60.]])

In [77]:
arr1

array([10, 20, 30])

In [78]:
arr1[1]

20

In [51]:
arr3

array([[10, 20, 30],
       [40, 50, 60]])

In [50]:
arr3[1][2]

60

In [28]:
arr3[1, 2]

60

In [29]:
arr3[0]

array([10, 20, 30])

In [79]:
arr3[:,1]

array([20, 50])

In [80]:
arr3dim

array([[[1, 2, 3],
        [3, 4, 5]],

       [[5, 6, 7],
        [7, 8, 9]]])

In [31]:
arr3dim[1]

array([[5, 6, 7],
       [7, 8, 9]])

In [81]:
arr3dim[:,:,1]

array([[2, 4],
       [6, 8]])

In [82]:
arr3dim.sum()

60

In [33]:
arr3dim.mean()

5.0

In [84]:
arr3dim.std()

2.3804761428476167

In [85]:
arr3dim.mean(0)

array([[3., 4., 5.],
       [5., 6., 7.]])

In [35]:
arr3dim.var()

5.666666666666667

In [36]:
arr3dim.min()

1

In [37]:
arr3dim.max()

9

In [86]:
for x in arr1:
    print(x)

10
20
30


In [88]:
for dim in arr3:
        print (dim)

[10 20 30]
[40 50 60]


In [89]:
for dim in arr3:
    for x in dim:
        print (x)

10
20
30
40
50
60


In [40]:
for x in np.nditer(arr3):
    print (x)

10
20
30
40
50
60


In [41]:
np.save("new_array", arr3)

In [42]:
np.load("new_array.npy")

array([[10, 20, 30],
       [40, 50, 60]])

In [43]:
np.savetxt("new_array.txt", arr3, delimiter='\t')

In [91]:
np.loadtxt("new_array.txt", delimiter='\t', dtype=int)

array([[10, 20, 30],
       [40, 50, 60]])